# These can be uncommented/changed to modify the default
# interpreter and file mode (permissions)
# default_shebang = "#!/bin/sh"
# default_mode = "0700"

# copy the date to my clipboard
[datecpy]
command = 'date "+%d-%m-%y" | xclip'  # only required option

# display htop in a new terminal window
[thtop]
command = "termite -e htop"
link = "th"  # create a hardlink to thtop called th

# print current git configuration
[gitcfg]
command = "git config --list | cat"
links = ["gitconfig", "gcfg"]  # create multiple links
mode = "755"  # allow anyone to read/execute this script

[test-perl]
shebang = "#!/usr/bin/env perl"
mode = "755"
# multi-line 'command'
command = '''
use strict;
use warnings;

my $greeting = "hello world";

print $greeting."\n";'''
