# These can be uncommented/changed to modify the default interpreter
# default_shebang = "#!/bin/sh"
# copy the date to my clipboard
[datecpy]
command = 'date "+%d-%m-%y" | xclip' # only required option

# display htop in a new terminal window
[thtop]
command = "termite -e htop"
link = "th"                 # create a hardlink to thtop called th

# print current git configuration
[gitcfg]
command = "git config --list | cat"
links = ["gitconfig", "gcfg"]       # create multiple links

[test-perl]
shebang = "#!/usr/bin/env perl"
# multi-line 'command'
command = '''
use strict;
use warnings;

my $greeting = "hello world";

print $greeting."\n";'''
